import type { Metadata } from 'next';
import { Inter, DM_Sans } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
/* import { dir } from 'i18next'; */
import { languages } from './i18n/settings';
import './globals.css';


export const inter = Inter({ subsets: ['latin'], variable: "--inter", });
export const dm_sans = DM_Sans({ subsets: ['latin'], variable: "--dm-sans", });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  /* const isDev = process.env.NODE_ENV === 'development' */
  const isDev = true;
  return (
    /* dir={dir(lng)} */
    <html lang={lng} suppressHydrationWarning={isDev}>
      <head>
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css'
          integrity='sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=='
          crossOrigin='anonymous'
          referrerPolicy='no-referrer'
        />
      </head>
      <body className={`overflow-x-hidden ${inter.variable} ${dm_sans.variable}`} suppressHydrationWarning={true}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
